name: Publish Joke Package

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes-really-publish-this" to confirm'
        required: true

jobs:
  publish:
    if: github.event.inputs.confirm == 'yes-really-publish-this'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # Required for trusted publishing

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # v7.1.5

      - name: Build package
        working-directory: packages/asyncio-storages-that-also-works-great-with-litestar-but-you-do-you
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          packages-dir: packages/asyncio-storages-that-also-works-great-with-litestar-but-you-do-you/dist/
