name: Publish Joke Package

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes-really-publish-this" to confirm'
        required: true

jobs:
  publish:
    if: github.event.inputs.confirm == 'yes-really-publish-this'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # Required for trusted publishing

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4

      - name: Build package
        working-directory: packages/asyncio-storages-that-also-works-great-with-litestar-but-you-do-you
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          packages-dir: packages/asyncio-storages-that-also-works-great-with-litestar-but-you-do-you/dist/
